name: Typecheck

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_ENV: development

defaults:
  run:
    shell: bash
    working-directory: '.'

jobs:
  typecheck:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/setup@v3
        with:
          runtime: node
          cache: true
          install: false
  
      - name: Install dependencies
        shell: bash
        run: pnpm ci
  
      - name: Type check
        shell: bash
        run: pnpm run check
